version: '3.8'
services:
  fintech:
    container_name: fintech
    build:
      context: ./
      dockerfile: ./build/docker/service/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    links:
      - fintech-db
    depends_on:
      - fintech-db

  fintech-db:
    restart: always
    container_name: fintech-db
    build: ./build/docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
    ports:
      - '3306:3306'
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
